# Generated by Django 3.1 on 2020-09-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
