# Generated by Django 3.1 on 2020-08-23 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_event', models.CharField(choices=[('ride', 'ride'), ('event', 'event')], default='ride', max_length=255)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_hour', models.CharField(default='10:00', max_length=10)),
                ('content', models.TextField()),
                ('subscribed_to_event', models.TextField(default='')),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
