# Generated by Django 3.1 on 2020-08-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200824_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='google_map',
            field=models.CharField(default='', max_length=500),
        ),
    ]
