# Generated by Django 3.1 on 2020-08-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200824_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='subscribed_to_event',
            field=models.TextField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
