# Generated by Django 3.1 on 2020-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_events_type_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='type_event',
            field=models.CharField(choices=[('ride', 'ride'), ('event', 'event')], default='ride', max_length=10),
        ),
    ]
