# Generated by Django 3.1 on 2020-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_events_attended_to_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attended_to_event',
            field=models.IntegerField(default=1),
        ),
    ]
