# Generated by Django 3.1 on 2020-09-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_registered_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_to_event',
            name='extra_passenger',
            field=models.IntegerField(default=1),
        ),
    ]
