# Generated by Django 3.1 on 2020-09-02 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_registered_to_event_extra_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_to_event',
            old_name='extra_passenger',
            new_name='passengers_counter',
        ),
        migrations.AlterField(
            model_name='registered_to_event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
