# Generated by Django 3.1 on 2020-09-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200902_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attended_to_event',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='subscribed_to_event',
            field=models.TextField(default=''),
        ),
    ]
