# Generated by Django 3.1 on 2020-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200902_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='events',
            name='subscribed_to_event',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
