# Generated by Django 3.1 on 2020-09-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='link_to_google_drive',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
