# Generated by Django 3.1 on 2020-08-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_store', models.CharField(choices=[('collaborations', 'collaborations'), ('sales', 'sales')], default='sales', max_length=30)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(blank=True, max_length=255, null=True)),
                ('link_to_store', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='default.jpeg', upload_to='store_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
