# Generated by Django 3.1 on 2020-09-11 07:48

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
