# Generated by Django 3.1 on 2020-09-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
